package cs2340.gatech.edu.cs2340spacetraderproject.model;

public enum Resources {
    NOSPECIALRESOURCES, MINERALRICH, MINERALPOOR, DESERT, LOTSOFWATER, RICHSOIL, POORSOIL, RICHFAUNA, LIFELESS,
    WEIRDMUSHROOMS, LOTSOFHERBS, ARTISITC, WARLIKE;
}
